apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deployment
  namespace: default
  labels:
    app: go-app-deployment
spec:
  selector:
    matchLabels:
      app: go-app-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: go-app-deployment
    spec:
      containers:
        - name: go-sample-app
          image: go-sample-app:latest
          ports:
            - containerPort: 8081